# Get node
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package and package-lock 
COPY package.json ./
COPY package-lock.json ./

# Run npm install silently
RUN npm install --silent

# Run docker start
CMD ["npm", "run", "docker"]
