version: "3.8"

services:
  client:
    build:
      context: .
      target: test-target
      args:
        npm_install_command: install
    volumes:
      - .:/usr/src/app:delegated
    ports:
      - 3000:3000
    command: npm run dev
    networks:
      - acol
  
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_USERNAME}
    ports:
      - 27017:27017