version: "3.8"

services:
  nextjs:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
      - /app/.next
      - /app/node_modules
    networks:
      - acol
    env_file:
      - .env.production
    ports:
      - 8080:3000
    depends_on:
      - mongodb
      - redis
  
  mongodb:
    image: mongo:latest
    hostname: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./dockerData/monogdb:/data/db
    networks:
      - acol
    ports:
      - 27020:17017
    environment:
      MONGO_INITDB_DATABASE: acol-dev

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: always
    command: 'redis-server'
    volumes:
      - ./dockerData/redis:/data/redis
    ports:
      - 6379:6379
    networks:
      - acol

networks:
  acol:
