version: "3.8"
services:
  acol:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: acol
    volumes:
      - ./src:/app/src
    networks:
      - acol-network
    ports:
      - 3000:3000

networks:
  acol-network:
    external: true
