version: "3.8"
services:
  acol-dev:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./src:/app/src
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
