import Head from "next/head";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";

// styles
import "../styles/globals.css";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>acol.dev</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar
        items={[
          { name: "Home", href: "/" },
          { name: "Example", href: "/example" },
        ]}
      />
      <Component {...pageProps} />
      <Footer />
    </>
  );
}

export default MyApp;
