// components
import Navbar from "@/components/Navbar";
import ThemeWrapper from "@/components/ThemeWrapper";
import Footer from "@/components/Footer";

// styles
import "@/styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const navbarItems = [{ name: "About", type: "internal", href: "/about" }];

  return (
    <html lang="en">
      <body>
        <ThemeWrapper>
          <Navbar items={navbarItems} />

          <main>{children}</main>

          <Footer />
        </ThemeWrapper>
      </body>
    </html>
  );
}
